name: Deploy to Minikube

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t certverify .

      - name: Load Docker image into Minikube
        run: |
          eval $(minikube -p minikube docker-env)
          docker tag certverify baimas/certverify:v1.0
          docker push baimas/certverify:v1.0

      - name: Deploy to Minikube
        run: kubectl apply -f deployment.yaml

      - name: Rollout Restart no Deployment
        run: kubectl rollout restart deployment/certverify
